//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAnh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanlynhansuEntities2 : DbContext
    {
        public QuanlynhansuEntities2()
            : base("name=QuanlynhansuEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblkhenthuong_kyluat> tblkhenthuong_kyluat { get; set; }
        public virtual DbSet<tblnhanvien> tblnhanviens { get; set; }
        public virtual DbSet<tblnhanvien_khenthuong_kyluat> tblnhanvien_khenthuong_kyluat { get; set; }
        public virtual DbSet<tblbophan> tblbophans { get; set; }
        public virtual DbSet<tblchungchi> tblchungchis { get; set; }
        public virtual DbSet<tblquyen> tblquyens { get; set; }
        public virtual DbSet<tbltaikhoan> tbltaikhoans { get; set; }
        public virtual DbSet<tblvitricongviec> tblvitricongviecs { get; set; }
    }
}
