//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkhenthuong_kyluat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblkhenthuong_kyluat()
        {
            this.tblnhanvien_khenthuong_kyluat = new HashSet<tblnhanvien_khenthuong_kyluat>();
        }
    
        public int PK_KTKL_iId { get; set; }
        public string KTKL_sTieuDe { get; set; }
        public Nullable<System.DateTime> KTKL_dThoiGianLap { get; set; }
        public Nullable<System.DateTime> KTKL_dThoiGianDuyet { get; set; }
        public Nullable<int> KTKL_iKinhPhi { get; set; }
        public string KTKL_sGhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnhanvien_khenthuong_kyluat> tblnhanvien_khenthuong_kyluat { get; set; }
    }
}
