//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblnhanvien_khenthuong_kyluat
    {
        public int PK_NV_KTKL_iId { get; set; }
        public int FK_NhanVien_iId { get; set; }
        public int FK_KTKL_iId { get; set; }
        public string NVKTKL_sNoiDung { get; set; }
    
        public virtual tblkhenthuong_kyluat tblkhenthuong_kyluat { get; set; }
        public virtual tblnhanvien tblnhanvien { get; set; }
    }
}
