//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltaikhoan
    {
        public int PK_TaiKhoan_iId { get; set; }
        public string TaiKhoan_sTen { get; set; }
        public string TaiKhoan_sMatKhau { get; set; }
        public string TaiKhoan_sTrangThai { get; set; }
        public Nullable<System.DateTime> TaiKhoan_sThoiGianCap { get; set; }
        public Nullable<int> FK_NhanVien_iId { get; set; }
        public Nullable<int> FK_Quyen_iId { get; set; }
    
        public virtual tblnhanvien tblnhanvien { get; set; }
        public virtual tblquyen tblquyen { get; set; }
    }
}
