//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblvitricongviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblvitricongviec()
        {
            this.tblnhanviens = new HashSet<tblnhanvien>();
        }
    
        public int PK_VCCV_iMaVCCV { get; set; }
        public string VCCV_sTenVCCV { get; set; }
        public string VCCV_sMoTaVCCV { get; set; }
        public int FK_BoPhan_MaBP { get; set; }
    
        public virtual tblbophan tblbophan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnhanvien> tblnhanviens { get; set; }
    }
}
